spring:
  profiles:
    active: dev
  application:
    name: meeting
  config:
    import: configserver:${SCHEME}://${ESC_CONFIG}:${ESC_CONFIG_PORT}
  cloud:
    config:
      name: meeting, naver-sms, aws